//
//  ActiveWorkoutScreen.swift
//  MCPStrength
//
//  The core screen of the product: the one a person uses standing in a gym
//  between sets. Large tap targets, obvious state, no density. Everything
//  reads from the Design layer — no raw colours or radii inline.
//

import SwiftUI
import SwiftData
import Combine

// MARK: - ActiveWorkoutScreen

/// The active workout logging screen. Owns one in-progress `Workout` and the
/// editing surface for its exercises and sets. `onFinish` / `onCancel` return
/// the caller (ContentView) to the root — this screen does not decide whether
/// the workout object survives; it only mutates it and reports.
struct ActiveWorkoutScreen: View {
    /// Set when Finish would throw away sets that have values typed in them.
    /// `.alert(item:)`-shaped for the same reason sheets are: the value and the
    /// presentation cannot disagree.
    @State private var pendingDiscard: WorkoutFinishing.DiscardSummary?

    /// Which option sheet is open, and for which exercise. Holds the EXERCISE,
    /// not an index: this screen's list can be reordered mid-session, and an
    /// index would silently start pointing at a different exercise.
    @State private var activeOption: ActiveOption?

    /// Whether the session-note editor is open.
    @State private var editingWorkoutNote = false

    struct ActiveOption: Identifiable {
        enum Kind { case note, stickyNote, rest, replace }
        let id = UUID()
        let exercise: WorkoutExercise
        let kind: Kind
    }

    /// Which set's own rest is being edited, opened by tapping its divider.
    /// Holds the SET rather than an index for the same reason `ActiveOption`
    /// holds the exercise: this list reorders mid-session.
    @State private var editingSetRest: SetRestEdit?

    struct SetRestEdit: Identifiable {
        let id = UUID()
        let set: WorkoutSet
    }

    @Environment(\.modelContext) private var context

    /// The user's global weight unit. Needed here, and not only inside
    /// `ExerciseBlock`, because the warm-up ramp is generated by THIS view —
    /// the menu action lives with the mutation, not with the row that displays
    /// the result.
    @Environment(\.weightUnit) private var globalWeightUnit

    /// Schedules the "rest complete" alert. Injected so a test host and UI
    /// preview mode can supply one that does nothing — see `RestNotifications`.
    let restNotifications: any RestNotificationScheduling

    let workout: Workout
    var onFinish: () -> Void = {}
    var onCancel: () -> Void = {}

    // All history, for the "Previous" column. Reverse-chronological sort makes
    // WorkoutHistory.previousSet's "most recent" pick cheap, and is harmless
    // when there is no history yet.
    @Query(filter: #Predicate<Workout> { $0.deletedAt == nil },
           sort: [SortDescriptor(\Workout.startedAt, order: .reverse)])
    private var allWorkouts: [Workout]

    @State private var now = Date()
    @State private var showingExercisePicker = false
    @State private var showingCancelConfirm = false

    // Rest timer is lifted to this owner so both the per-set progress bars and
    // the top-bar timer button can reach it. `restingSetID` identifies which
    // set's divider is currently live; the model itself carries no set info.
    @State private var restTimer = RestTimer()
    @State private var restingSetID: UUID?
    @State private var showingRestControls = false

    // Non-nil while an exercise title is being dragged. Every block
    // collapses to its title row so the user can actually see (and
    // drop onto) exercises that would otherwise be two screens of
    // sets away.
    @State private var draggingExerciseID: UUID?

    /// Which exercise the dragged one is currently hovering over.
    ///
    /// Separate from `draggingExerciseID`, which records what was LIFTED. This
    /// is where it would LAND, and nothing tracked it before — so a reorder
    /// was performed blind: the list collapsed, and then nothing moved, opened
    /// a gap, or lit up until the drop had already happened.
    @State private var dropTargetExerciseID: UUID?

    private let ticker = Timer.publish(every: 1, on: .main, in: .common).autoconnect()

    /// Whether the current rest has already buzzed.
    ///
    /// The ticker fires every second, and a rest stays `.finished` for every
    /// second after it ends — so without a latch the phone would vibrate once a
    /// second until the next set was ticked. Cleared in `startRest`, which is
    /// the only place a new rest begins.
    @State private var restCompletionSignalled = false

    var body: some View {
        VStack(spacing: 0) {
            header

            ScrollView {
                VStack(spacing: Spacing.spacious) {
                    workoutHeaderBlock

                    ForEach(sortedExercises, id: \.id) { workoutExercise in
                        ExerciseBlock(
                            workoutExercise: workoutExercise,
                            allWorkouts: allWorkouts,
                            inProgressWorkout: workout,
                            now: now,
                            restTimer: restTimer,
                            restingSetID: restingSetID,
                            isCollapsed: isReordering,
                            onReorderLift: { draggingExerciseID = workoutExercise.id },
                            onReorderEnded: {
                                draggingExerciseID = nil
                                dropTargetExerciseID = nil
                            },
                            onStartRest: { setID, seconds in
                                startRest(for: setID, seconds: seconds)
                            },
                            onOpenRestControls: {
                                showingRestControls = true
                            },
                            onOption: { option in
                                handleOption(option, for: workoutExercise)
                            },
                            onEditRest: { set in
                                editingSetRest = SetRestEdit(set: set)
                            }
                        )
                        // The insertion marker. `.draggable`/`.dropDestination`
                        // report a DROP, not a continuous position, so there is
                        // no in-between layout to animate — but `isTargeted`
                        // does say which block is under the finger, and a rule
                        // above that block answers the actual question: where
                        // will this land if I let go.
                        //
                        // A rule rather than an opened gap: inserting real space
                        // would reflow a list that is already collapsed
                        // mid-drag, and everything below would shift under the
                        // thumb while the user is aiming at it.
                        .overlay(alignment: .top) {
                            // Deliberately NOT also checking
                            // `draggingExerciseID != workoutExercise.id`.
                            //
                            // That check looks right — do not mark the block
                            // you are dragging — and it silently suppressed the
                            // marker on the block you were AIMING at. The
                            // `isTargeted` handler below sets
                            // `draggingExerciseID` to whatever it is hovering
                            // when that value is still nil, because the drag
                            // payload cannot be read until the drop and any
                            // non-nil id is enough to collapse the list. So the
                            // first block hovered became "the one being
                            // dragged" as far as this condition was concerned,
                            // and its marker never drew. Dropping a block onto
                            // itself is already a no-op in
                            // `handleExerciseDrop`, so there is nothing to
                            // protect against here.
                            if dropTargetExerciseID == workoutExercise.id {
                                Capsule()
                                    .fill(Theme.accent)
                                    .frame(height: 3)
                                    .padding(.horizontal, Spacing.compact)
                                    .offset(y: -Spacing.compact)
                                    .transition(.opacity)
                            }
                        }
                        .animation(.snappy(duration: 0.15), value: dropTargetExerciseID)
                        .dropDestination(for: String.self) { items, _ in
                            dropTargetExerciseID = nil
                            return handleExerciseDrop(items, onto: workoutExercise)
                        } isTargeted: { targeted in
                            // Payload isn't readable until drop. Any non-nil
                            // id is enough to collapse the list.
                            if targeted, draggingExerciseID == nil {
                                draggingExerciseID = workoutExercise.id
                            }
                            if targeted {
                                dropTargetExerciseID = workoutExercise.id
                            } else if dropTargetExerciseID == workoutExercise.id {
                                dropTargetExerciseID = nil
                            }
                        }
                    }

                    endOfListDropZone

                    bottomActions
                }
                .padding(.horizontal, Spacing.screenMargin)
                .padding(.vertical, Spacing.spacious)
            }
        }
        .background(Theme.surface)
        // THE ONLY PLACE the rest notification is decided. Every way a rest can
        // change — start, pause, resume, ±15, reset, skip — changes this value,
        // so watching the value covers all of them and any that get added
        // later. See RestNotificationRule for why this is a rule rather than a
        // call at each mutation site.
        .onChange(of: restTimer) { _, timer in
            reconcileRestNotification(timer)
        }
        .onDisappear {
            // Finishing or cancelling leaves a rest armed otherwise, and the
            // alert would arrive for a workout that is over. NOT tied to
            // backgrounding: a rest running while the app is in the background
            // is exactly the case the notification exists for.
            Task { await restNotifications.cancel() }
        }
        .sheet(isPresented: $showingExercisePicker) {
            ExercisesScreen(onSelect: { exercise in
                addExercise(exercise)
                showingExercisePicker = false
            })
        }
        .sheet(item: $activeOption) { option in
            optionSheet(for: option)
        }
        .sheet(item: $editingSetRest) { edit in
            RestTimerSheet(scope: .oneSet, current: edit.set.restSeconds) {
                edit.set.restSeconds = $0
                edit.set.markEdited()
            }
        }
        .sheet(isPresented: $editingWorkoutNote) {
            ExerciseNoteSheet(
                isSticky: false,
                exerciseName: workout.name,
                initialText: workout.note
            ) {
                workout.note = $0
                workout.markEdited()
            }
        }
        .sheet(isPresented: $showingRestControls) {
            RestControlsSheet(
                restTimer: $restTimer,
                now: now
            )
        }
        .confirmationDialog(
            "Cancel this workout? Sets logged so far will be discarded.",
            isPresented: $showingCancelConfirm,
            titleVisibility: .visible
        ) {
            Button("Cancel Workout", role: .destructive) { cancel() }
            Button("Keep Logging", role: .cancel) {}
        }
        // Driven BY the value, not by a separate flag: `presenting:` takes the
        // summary itself, so the alert and the thing it describes cannot
        // disagree. Same reasoning as .sheet(item:) in docs/04-status.md.
        .alert(
            "Discard unfinished sets?",
            isPresented: Binding(
                get: { pendingDiscard != nil },
                set: { if !$0 { pendingDiscard = nil } }
            ),
            presenting: pendingDiscard
        ) { _ in
            Button("Discard and Finish", role: .destructive) { commitFinish() }
            Button("Keep Logging", role: .cancel) { pendingDiscard = nil }
        } message: { summary in
            Text(discardMessage(for: summary))
        }
        .onReceive(ticker) { instant in
            now = instant
            signalRestCompletionIfNeeded(at: instant)
        }
    }

    // MARK: - Header

    private var header: some View {
        HStack(spacing: Spacing.comfortable) {
            Button {
                if restingSetID != nil {
                    showingRestControls = true
                }
            } label: {
                Image(systemName: "timer")
                    .font(Typography.body)
                    .foregroundStyle(restingSetID == nil ? Theme.textSecondary : Theme.accent)
                    .frame(width: 40, height: 40)
                    .background(Theme.fieldFill, in: .rect(cornerRadius: Radius.chip))
            }
            .buttonStyle(.plain)

            Spacer()

            Text(formatTime(elapsedSeconds))
                .font(Typography.secondary)
                .foregroundStyle(Theme.textSecondary)
                .monospacedDigit()

            Spacer()

            Button("Finish") { finish() }
                .buttonStyle(.primaryAction)
                .frame(maxWidth: 140)
        }
        .padding(.horizontal, Spacing.screenMargin)
        .padding(.vertical, Spacing.compact)
    }

    // MARK: - Workout header block

    // The title strip between the top bar and the first exercise: the workout
    // name, then the start date and the running elapsed time. The name comes
    // straight from the model — this view never generates or renames it.
    private var workoutHeaderBlock: some View {
        VStack(alignment: .leading, spacing: Spacing.compact) {
            // The header DISPLAYS the session note; the button to write one
            // lives at the bottom, next to Finish. Two entry points for the
            // same field would be clutter, and the bottom is where the note
            // actually gets written.
            Text(workout.name)
                .font(Typography.title)
                .foregroundStyle(Theme.textPrimary)
                .frame(maxWidth: .infinity, alignment: .leading)

            if let note = workout.note, !note.isEmpty {
                ExpandableNote(text: note, kind: .session)
            }

            HStack(spacing: Spacing.spacious) {
                Label {
                    Text(workoutDateText)
                        .font(Typography.secondary)
                        .foregroundStyle(Theme.textSecondary)
                } icon: {
                    Image(systemName: "calendar")
                        .font(Typography.secondary)
                        .foregroundStyle(Theme.textSecondary)
                }

                Label {
                    Text(formatTime(elapsedSeconds))
                        .font(Typography.secondary)
                        .foregroundStyle(Theme.textSecondary)
                        .monospacedDigit()
                } icon: {
                    Image(systemName: "clock")
                        .font(Typography.secondary)
                        .foregroundStyle(Theme.textSecondary)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.bottom, Spacing.compact)
        // Same 0.4 the rest-progress border already uses — dim the
        // chrome so only the collapsed title rows read as drop targets.
        .opacity(isReordering ? 0.4 : 1)
    }

    private var workoutDateText: String {
        workout.startedAt.formatted(.dateTime.month().day().year())
    }

    // MARK: - Bottom actions

    /// A drop target after the last exercise, meaning "put it at the end".
    ///
    /// **Without this the last position is unreachable.** Dropping onto a block
    /// inserts BEFORE that block — that is what the insertion rule above it
    /// means — so every position in the list is expressible except the one
    /// after the final exercise. You could move anything anywhere except last,
    /// and nothing on screen explained why the bottom of the list refused to
    /// light up.
    ///
    /// Only present while a drag is in flight. A permanent invisible strip
    /// under the exercises would eat taps meant for the buttons below it, and
    /// there is nothing to aim at when nothing is being dragged.
    ///
    /// The height is deliberate: 44pt is the minimum comfortable target, and
    /// this one is aimed at with a card held under the thumb, so it gets the
    /// same treatment as any other control rather than being a hairline.
    @ViewBuilder
    private var endOfListDropZone: some View {
        if isReordering {
            ZStack(alignment: .top) {
                Color.clear
                if dropTargetExerciseID == Self.endOfListTargetID {
                    Capsule()
                        .fill(Theme.accent)
                        .frame(height: 3)
                        .padding(.horizontal, Spacing.compact)
                }
            }
            .frame(height: 44)
            .contentShape(Rectangle())
            .animation(.snappy(duration: 0.15), value: dropTargetExerciseID)
            .dropDestination(for: String.self) { items, _ in
                dropTargetExerciseID = nil
                return handleExerciseDropAtEnd(items)
            } isTargeted: { targeted in
                if targeted {
                    dropTargetExerciseID = Self.endOfListTargetID
                } else if dropTargetExerciseID == Self.endOfListTargetID {
                    dropTargetExerciseID = nil
                }
            }
        }
    }

    /// Stands in for "past the last exercise" in `dropTargetExerciseID`, which
    /// otherwise only ever holds a real exercise's id. A sentinel rather than a
    /// second `@State` flag so the two cannot both be set and disagree about
    /// where the marker goes.
    private static let endOfListTargetID = UUID()

    private var bottomActions: some View {
        VStack(spacing: Spacing.comfortable) {
            Button("Add Exercises") { showingExercisePicker = true }
                .buttonStyle(.tintedAccent)

            // A SUMMARY note belongs here, not at the top. It is written at the
            // END of a session — "slept badly", "gym was packed, rushed the
            // last two" — so the entry point sits where the thumb already is
            // when finishing, immediately above Cancel and a scroll from
            // Finish. Putting it in the header meant scrolling back up to write
            // the one thing you only know once you are done.
            Button(hasSessionNote ? "Edit Workout Note" : "Add Workout Note") {
                editingWorkoutNote = true
            }
            .buttonStyle(.tintedAccent)

            Button("Cancel Workout") { showingCancelConfirm = true }
                .buttonStyle(.tintedDestructive)
        }
        .opacity(isReordering ? 0.4 : 1)
    }

    private var hasSessionNote: Bool {
        !(workout.note ?? "").isEmpty
    }

    // MARK: - Derived

    private var sortedExercises: [WorkoutExercise] {
        workout.liveExercises
    }

    private var isReordering: Bool { draggingExerciseID != nil }

    private var elapsedSeconds: Int {
        max(0, Int(now.timeIntervalSince(workout.startedAt)))
    }

    // MARK: - Mutations

    private func addExercise(_ exercise: Exercise) {
        let nextOrder = (workout.liveExercises.map(\.order).max() ?? -1) + 1
        let workoutExercise = WorkoutExercise(order: nextOrder)
        workoutExercise.workout = workout
        workoutExercise.exercise = exercise
        context.insert(workoutExercise)

        let firstSet = WorkoutSet(order: 0)
        firstSet.workoutExercise = workoutExercise
        context.insert(firstSet)
    }

    /// Tapping Finish. Asks first ONLY when there is something to lose.
    ///
    /// Unticked sets are discarded on finish (WorkoutFinishing explains why),
    /// and that destroys numbers the user may have typed and simply forgotten
    /// to tick. Confirming every finish would be nagging; confirming none of
    /// them loses a set to a mis-tap. So the prompt appears only when a doomed
    /// set actually has values in it.
    // MARK: - Exercise options

    /// The same menu as the template editor, answered differently: this screen
    /// edits PERSISTED models, so every change marks the row for sync and a
    /// removal is a soft delete rather than dropping an array element.
    private func handleOption(_ option: ExerciseOption, for exercise: WorkoutExercise) {
        switch option {
        case .addNote:
            activeOption = ActiveOption(exercise: exercise, kind: .note)
        case .addStickyNote:
            activeOption = ActiveOption(exercise: exercise, kind: .stickyNote)
        case .updateRestTimers:
            activeOption = ActiveOption(exercise: exercise, kind: .rest)
        case .replaceExercise:
            activeOption = ActiveOption(exercise: exercise, kind: .replace)
        case .addWarmupSets:
            addWarmupSets(to: exercise)
        case .createSuperset:
            toggleSuperset(for: exercise)
        case .removeExercise:
            // Soft, unlike the discard at Finish. This row may already exist on
            // the server if the workout was finished and reopened, and the
            // cascade to its sets has to propagate either way.
            SoftDelete.workoutExercise(exercise)
        }
    }

    /// Generate the warm-up ramp for this exercise, REPLACING whatever
    /// warm-ups are already there.
    ///
    /// Replace, not append, and that is the decision rather than a shortcut.
    /// The second tap is almost always somebody who typed the working weight
    /// AFTER adding the exercise and wants the ramp recalculated; appending
    /// would give them six warm-up sets to delete. Drake was explicit that
    /// this overwrites even warm-ups he had adjusted by hand — it is the
    /// standard calculation, applied fresh.
    ///
    /// The working weight is the first live set that is NOT a warm-up and has
    /// a weight typed in. No such set means no ramp: `WarmupSets` returns an
    /// empty plan and this does nothing, rather than inventing 0 lb warm-ups
    /// (AGENTS.md rule 4).
    ///
    /// Replaced warm-ups are TOMBSTONED, not deleted. The hard delete at
    /// Finish is safe only because an unfinished workout can never have been
    /// pushed; this action is reachable on a workout that was finished and
    /// reopened, exactly like `removeExercise` above, so the delete has to be
    /// able to travel.
    private func addWarmupSets(to exercise: WorkoutExercise) {
        let live = exercise.liveSets
        let working = live.first { $0.setType != .warmup && $0.weight != nil }

        // The ramp runs entirely in the user's unit — working weight converted
        // in, bar weight read in that unit, steps converted back on the way
        // out. `WarmupSets` explains why it is the one calculation that leaves
        // canonical kilograms: a plate increment is a fact about a gym.
        let unit = WeightUnits.displayUnit(
            override: exercise.exercise?.weightUnitOverride,
            global: globalWeightUnit
        )
        let plan = WarmupSets.plan(
            forWorkingWeight: working?.weight.map {
                WeightUnits.displayed(from: $0, in: unit)
            },
            barWeight: exercise.exercise?.barType?.weight(in: unit),
            in: unit
        )
        guard !plan.isEmpty else { return }

        for set in live where set.setType == .warmup {
            set.markDeleted()
        }

        // Warm-ups occupy the first slots and the survivors shift down, because
        // `liveSets` sorts on `order` and a ramp after the working sets is not
        // a ramp. Every survivor whose number actually moves is marked — the
        // reorder loops on this screen learned that the hard way.
        for (index, step) in plan.enumerated() {
            let warmup = WorkoutSet(
                order: index,
                setType: step.setType,
                weight: WeightUnits.kilograms(from: step.weight, in: unit),
                reps: step.reps,
                restSeconds: exercise.defaultRestSeconds
            )
            warmup.workoutExercise = exercise
            context.insert(warmup)
        }
        for (offset, set) in live.filter({ $0.setType != .warmup }).enumerated() {
            let newOrder = plan.count + offset
            guard set.order != newOrder else { continue }
            set.order = newOrder
            set.markEdited()
        }
        exercise.markEdited()
    }

    /// Pair with the exercise ABOVE, or leave the current group. See the
    /// template editor's copy for the reasoning — a superset is round-robin in
    /// list order, so "join the one before me" is the only rule that needs no
    /// second selection UI.
    private func toggleSuperset(for exercise: WorkoutExercise) {
        let ordered = workout.liveExercises
        guard let index = ordered.firstIndex(where: { $0.id == exercise.id }) else { return }

        if exercise.supersetGroupID != nil {
            exercise.supersetGroupID = nil
            exercise.markEdited()
            return
        }
        guard index > 0 else { return }
        let previous = ordered[index - 1]
        let group = previous.supersetGroupID ?? UUID()
        previous.supersetGroupID = group
        previous.markEdited()
        exercise.supersetGroupID = group
        exercise.markEdited()
    }

    @ViewBuilder
    private func optionSheet(for option: ActiveOption) -> some View {
        let exercise = option.exercise
        let name = exercise.exercise?.name ?? "Exercise"
        switch option.kind {
        case .note:
            ExerciseNoteSheet(isSticky: false, exerciseName: name, initialText: exercise.note) {
                exercise.note = $0
                exercise.markEdited()
            }
        case .stickyNote:
            ExerciseNoteSheet(isSticky: true, exerciseName: name, initialText: exercise.stickyNote) {
                exercise.stickyNote = $0
                exercise.markEdited()
            }
        case .rest:
            RestTimerSheet(
                scope: .wholeExercise(exerciseName: name),
                current: exercise.defaultRestSeconds
            ) { seconds in
                // BOTH halves, and the second one is the fix. Writing only the
                // exercise default changed what a FUTURE set would inherit and
                // left every set already on screen alone, which reads as the
                // control doing nothing.
                exercise.defaultRestSeconds = seconds
                exercise.markEdited()
                for set in exercise.liveSets {
                    guard set.restSeconds != seconds else { continue }
                    set.restSeconds = seconds
                    // Every row whose value actually moved, or it silently
                    // stops syncing — AGENTS.md rule 3.
                    set.markEdited()
                }
            }
        case .replace:
            ExercisesScreen(onSelect: { picked in
                exercise.exercise = picked
                exercise.markEdited()
                activeOption = nil
            })
        }
    }

    private func finish() {
        let summary = WorkoutFinishing.discardSummary(for: workout)
        if summary.hasEnteredValues {
            pendingDiscard = summary
        } else {
            commitFinish()
        }
    }

    /// Names what is about to be lost, specifically. "Some sets weren't
    /// completed" is a shrug; "2 sets on Barbell Row" is something the user can
    /// check against what they remember doing.
    private func discardMessage(for summary: WorkoutFinishing.DiscardSummary) -> String {
        let sets = summary.setCount == 1 ? "1 set has" : "\(summary.setCount) sets have"
        var text = "\(sets) weights or reps typed in but were never ticked off. "
        if summary.exerciseCount == 1 {
            text += "1 exercise will be removed from this workout. "
        } else if summary.exerciseCount > 1 {
            text += "\(summary.exerciseCount) exercises will be removed from this workout. "
        }
        return text + "Finishing keeps only the sets you completed."
    }

    private func commitFinish() {
        pendingDiscard = nil
        WorkoutFinishing.finish(workout, elapsedSeconds: elapsedSeconds, in: context)
        onFinish()
    }

    private func cancel() {
        // A REAL delete, and now provably safe. An unfinished workout is not
        // eligible to push (PushFilter.shouldPush), so a cancelled one has
        // never reached the server and there is nothing out there for a
        // tombstone to propagate to. Keeping one would store — and later
        // upload — a record of a workout that never happened.
        //
        // This was a soft delete until the "only finished workouts sync" rule
        // existed, because nothing could then PROVE the workout had not been
        // pushed. The rule turned a guess into a guarantee.
        context.delete(workout)
        onCancel()
    }

    /// Begin the rest countdown for the set the user just checked complete.
    /// Replaces any rest already in flight (e.g. the user checks a second set
    /// before the first rest finished).
    /// Bring the pending notification in line with the timer.
    ///
    /// Lives on THIS view, not on `ExerciseBlock`: the timer, the resting set
    /// and the workout are all owned here, and a block only knows about its own
    /// exercise. (It was written into the block first and did not compile,
    /// which is the useful kind of mistake — the scope error was the design
    /// telling me where the state lives.)
    ///
    /// The exercise name is resolved here rather than inside the rule, because
    /// the rule is pure and knows nothing about workouts — it answers "when",
    /// this answers "about what".
    private func reconcileRestNotification(_ timer: RestTimer) {
        let plan = RestNotificationRule.plan(for: timer, at: Date())
        let name = restingSetID
            .flatMap { id in
                workout.liveExercises.first { $0.liveSets.contains { $0.id == id } }
            }?
            .exercise?.name
        Task {
            switch plan {
            case .schedule(let date):
                await restNotifications.schedule(at: date, exerciseName: name)
            case .cancel:
                await restNotifications.cancel()
            }
        }
    }

    /// Buzz once, the moment a rest runs out, while the app is open.
    ///
    /// **`status(at:) == .finished`, NOT `isFinished(at:)`** — and the
    /// difference is the whole behaviour. `isFinished` also reports true for a
    /// SKIPPED rest, so using it would vibrate at the exact moment the user
    /// pressed Skip to say they were done resting. `.finished` is only
    /// reachable by a running countdown reaching zero.
    ///
    /// This covers the app-in-front case, which the notification handles
    /// badly: iOS decides whether a banner vibrates based on the user's own
    /// settings, and a phone face-down on a bench with the app open is exactly
    /// when you need to FEEL it rather than see it. The notification still
    /// covers backgrounded and locked.
    private func signalRestCompletionIfNeeded(at instant: Date) {
        guard !restCompletionSignalled else { return }
        guard restTimer.status(at: instant) == .finished else { return }
        restCompletionSignalled = true
        UINotificationFeedbackGenerator().notificationOccurred(.success)
    }

    private func startRest(for setID: UUID, seconds: Int) {
        restingSetID = setID
        restTimer = RestTimer()
        restTimer.start(duration: TimeInterval(max(0, seconds)), at: Date())
        // Arm the buzz for THIS rest. Every new rest gets one.
        restCompletionSignalled = false
    }

    /// Drop onto an exercise row: insert at that row's position after the
    /// dragged id has been removed (the ListOrdering index convention).
    /// Same-list — source and destination are the workout's ordered ids.
    /// Move the dragged exercise to the END of the list.
    ///
    /// Shares `ListOrdering.move` with the onto-a-block path rather than
    /// hand-rolling an append, so both routes renumber identically and there is
    /// one rule for what an order list looks like afterwards.
    private func handleExerciseDropAtEnd(_ items: [String]) -> Bool {
        defer { draggingExerciseID = nil }
        guard let raw = items.first, let id = UUID(uuidString: raw) else { return false }

        let ids = sortedExercises.map(\.id)
        guard ids.contains(id) else { return false }
        // Already last: nothing to do, and reporting success stops the drop
        // reading as a rejection.
        guard ids.last != id else { return true }

        var dest = ids
        dest.removeAll { $0 == id }
        let result = ListOrdering.move(id, from: ids, to: ids, at: dest.count)
        let byID = Dictionary(uniqueKeysWithValues: workout.liveExercises.map { ($0.id, $0) })
        for (i, eid) in result.destination.enumerated() {
            guard byID[eid]?.order != i else { continue }
            byID[eid]?.order = i
            byID[eid]?.markEdited()
        }
        return true
    }

    private func handleExerciseDrop(_ items: [String], onto target: WorkoutExercise) -> Bool {
        defer { draggingExerciseID = nil }
        guard let raw = items.first, let id = UUID(uuidString: raw) else { return false }
        if id == target.id { return true }

        let ids = sortedExercises.map(\.id)
        var dest = ids
        dest.removeAll { $0 == id }
        guard let index = dest.firstIndex(of: target.id) else { return false }

        let result = ListOrdering.move(id, from: ids, to: ids, at: index)
        let byID = Dictionary(uniqueKeysWithValues: workout.liveExercises.map { ($0.id, $0) })
        for (i, eid) in result.destination.enumerated() {
            byID[eid]?.order = i
            byID[eid]?.markEdited()
        }
        return true
    }
}

// MARK: - ExerciseBlock

/// One exercise's section: name, column header, the set rows with rest
/// dividers between them, and the "+ Add Set" button. While a reorder
/// drag is active the block collapses to the title row — a full set
/// list is taller than the screen, so without collapsing you cannot
/// drop onto an exercise two screens away.
private struct ExerciseBlock: View {
    let workoutExercise: WorkoutExercise
    let allWorkouts: [Workout]
    let inProgressWorkout: Workout
    let now: Date
    let restTimer: RestTimer
    let restingSetID: UUID?
    let isCollapsed: Bool
    var onReorderLift: () -> Void = {}
    var onReorderEnded: () -> Void = {}
    let onStartRest: (UUID, Int) -> Void
    let onOpenRestControls: () -> Void
    /// The menu selection, handled by the screen — this block owns no
    /// behaviour of its own.
    var onOption: (ExerciseOption) -> Void = { _ in }
    /// A rest divider was tapped. Handled by the screen for the same reason.
    var onEditRest: (WorkoutSet) -> Void = { _ in }

    /// The user's global weight unit, published by `ContentView`. Combined
    /// with this exercise's own override in `displayUnit` below.
    @Environment(\.weightUnit) private var globalWeightUnit

    /// The unit every weight in THIS block is read and written in.
    ///
    /// Resolved once per block rather than per row, because the override is a
    /// property of the exercise and every set under it is the same lift. When
    /// the four preference fields move onto `ExercisePreference`
    /// (docs/06-sync.md) this is the line that changes, and it is the only one.
    private var displayUnit: WeightUnit {
        WeightUnits.displayUnit(
            override: workoutExercise.exercise?.weightUnitOverride,
            global: globalWeightUnit
        )
    }

    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.comfortable) {
            // The name is still the DRAG HANDLE — long-pressing it starts a
            // reorder — so the menu button sits beside it rather than inside
            // it. Putting a Menu inside a `.draggable` makes the two gestures
            // fight: a long press has to be either a lift or a menu.
            HStack(spacing: Spacing.compact) {
                Text(workoutExercise.exercise?.name ?? "Unknown Exercise")
                    .font(Typography.body.weight(.semibold))
                    .foregroundStyle(Theme.accent)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .contentShape(Rectangle())
                    .draggable(workoutExercise.id.uuidString) {
                        Text(workoutExercise.exercise?.name ?? "Unknown Exercise")
                            .font(Typography.body.weight(.semibold))
                            .foregroundStyle(Theme.accent)
                            .onAppear(perform: onReorderLift)
                            .onDisappear(perform: onReorderEnded)
                    }

                // Hidden while reordering: the whole point of the collapse is
                // to get the list small enough to drag across, and a row of
                // menu buttons is noise you cannot tap mid-drag anyway.
                if !isCollapsed {
                    ExerciseOptionsMenu(
                        hasNote: !(workoutExercise.note ?? "").isEmpty,
                        hasStickyNote: !(workoutExercise.stickyNote ?? "").isEmpty,
                        isInSuperset: workoutExercise.supersetGroupID != nil,
                        onSelect: { onOption($0) }
                    )
                }
            }

            // A sticky note is pinned BELOW the name and stays visible while
            // logging — that is the entire difference between it and a note,
            // which lives behind the menu.
            if let sticky = workoutExercise.stickyNote, !sticky.isEmpty, !isCollapsed {
                ExpandableNote(text: sticky, kind: .exercise, tint: Theme.warmup)
            }

            if !isCollapsed {
                SetRowColumnHeader(trailingIcon: "checkmark", unit: displayUnit)

                VStack(spacing: 0) {
                    ForEach(Array(sortedSets.enumerated()), id: \.element.id) { index, set in
                        SetRow(
                            setType: Binding(get: { set.setType }, set: { set.setType = $0; set.markEdited() }),
                            setNumber: workingNumbers[index],
                            previousText: previousText(for: set, position: previousPositions[index]),
                            weight: Binding(get: { set.weight }, set: { set.weight = $0; set.markEdited() }),
                            unit: displayUnit,
                            prescription: Binding(
                                get: { RepRange.fromWorkout(reps: set.reps) },
                                set: { newValue in
                                    // A performance has a number, not a range — only
                                    // .fixed (or nil) is ever written here; a range
                                    // is rejected by the parser with allowRange:false.
                                    set.reps = newValue.flatMap { range -> Int? in
                                        if case .fixed(let n) = range { return n }
                                        return nil
                                    }
                                    set.markEdited()
                                }
                            ),
                            allowRange: false,
                            rpe: Binding(get: { set.rpe }, set: { set.rpe = $0; set.markEdited() }),
                            trailing: .completion(
                                isCompleted: set.isCompleted,
                                onToggle: { toggleComplete(set) }
                            ),
                            onDelete: { deleteSet(set) }
                        )

                        // EVERY set gets a rest row, including the last one.
                        //
                        // This used to special-case the final set: progress bar
                        // while resting, nothing otherwise. The reasoning was
                        // that a divider "between" sets has nothing to sit
                        // between at the bottom of the list — and it was wrong
                        // twice over. The rest after an exercise's last set is
                        // the rest before the next EXERCISE, which is a real
                        // rest you take; and hiding it left that set's rest
                        // with no way to tap and edit it, since editing goes
                        // through the divider.
                        //
                        // The reference app draws it too
                        // (`Workout screen/` — the F Shoulders screenshot ends
                        // set 3 with a 2:00 divider before "+ Add Set"). An
                        // earlier reading of a DIFFERENT reference screenshot
                        // concluded the opposite, from a single exercise whose
                        // last set was a drop set. One sample was not enough to
                        // support the general claim it was used for.
                        restDividerOrBar(for: set)
                    }
                }

                AddSetButton(label: "+ Add Set (\(formatTime(defaultRestSeconds)))") {
                    addSet()
                }
            }
        }
    }

    private var sortedSets: [WorkoutSet] {
        workoutExercise.liveSets
    }

    // Working-set numbers parallel to `sortedSets`: only `.normal` sets consume
    // a number, so warm-ups / drop sets / failure sets render a letter and the
    // numbering of normal sets continues past them (docs/01-data-model.md § SetType).
    /// Which row the Previous column reads history from. Warm-ups count in
    /// their own sequence — see `SetNumbering.positionsWithinKind`.
    private var previousPositions: [Int] {
        SetNumbering.positionsWithinKind(for: sortedSets.map(\.setType))
    }

    private var workingNumbers: [Int?] {
        SetNumbering.workingNumbers(for: sortedSets.map(\.setType))
    }

    /// The rest a newly added set inherits, and what the Add Set button
    /// advertises.
    ///
    /// > **This was hardcoded to `90` and that was the whole bug on this
    /// > screen.** The options menu wrote `defaultRestSeconds` on the exercise
    /// > and this read a literal, so the two were never connected: the button
    /// > always said 1:30 and always appended a 90-second set no matter what
    /// > the user chose. It looked like the menu was being ignored because it
    /// > was. The 90 still exists as the MODEL's declaration default, which is
    /// > where a default belongs.
    private var defaultRestSeconds: Int {
        workoutExercise.defaultRestSeconds
    }

    // MARK: - Rest divider / progress bar

    /// True when this set owns the live rest countdown and the countdown is
    /// still visibly running (not yet elapsed and not skipped).
    private func isResting(_ set: WorkoutSet) -> Bool {
        restingSetID == set.id && !restTimer.isFinished(at: now)
    }

    /// Renders the divider below `set`. When that set's rest is running the
    /// thin rule is replaced by a full-width depleting progress bar; otherwise
    /// the existing thin-rule-plus-time divider is used.
    @ViewBuilder
    private func restDividerOrBar(for set: WorkoutSet) -> some View {
        if isResting(set) {
            RestProgressBar(
                timer: restTimer,
                now: now,
                onTap: onOpenRestControls
            )
        } else {
            // Green once the set above it is ticked — the rest was taken, so it
            // belongs to the completed run rather than to what is still ahead.
            RestDivider(
                restSeconds: set.restSeconds,
                isCompleted: set.isCompleted,
                onTap: { onEditRest(set) }
            )
        }
    }

    // MARK: - Completion

    /// Toggle the set's completion and start a rest when it becomes complete.
    /// Owns the model mutation that the shared `SetRow` deliberately does not.
    private func toggleComplete(_ set: WorkoutSet) {
        set.isCompleted.toggle()
        set.completedAt = set.isCompleted ? Date() : nil
        set.markEdited()
        // Starting a rest only fires when the set becomes complete —
        // unchecking does not start one.
        if set.isCompleted {
            onStartRest(set.id, set.restSeconds)
        }
    }

    // MARK: - Previous

    /// `position` is this row's index WITHIN ITS KIND, so a warm-up reads last
    /// time's warm-ups and a working row reads last time's working sets.
    private func previousText(for set: WorkoutSet, position: Int) -> String {
        guard let exercise = workoutExercise.exercise else { return "—" }
        let prev = WorkoutHistory.previousSet(
            for: exercise,
            at: position,
            like: set.setType,
            in: allWorkouts,
            excluding: inProgressWorkout
        )
        return PreviousText.format(prev, in: displayUnit)
    }

    /// Remove one set, from the swipe affordance on its row.
    ///
    /// **A TOMBSTONE, not a real delete** — AGENTS.md rule 1. This screen is
    /// reachable on a workout that was finished and reopened, so the row may
    /// already exist on the server, and a hard delete could never reach a
    /// device that was offline when it happened. The one deliberate hard
    /// delete in this app is discarding unticked sets at Finish, and that is
    /// safe only because an unfinished workout is ineligible to push
    /// (`PushFilter`); this action has no such guarantee.
    ///
    /// The survivors are renumbered so `order` stays dense. `liveSets` sorts
    /// on it, and leaving a hole is harmless today but makes every later
    /// insert reason about gaps.
    private func deleteSet(_ set: WorkoutSet) {
        let exercise = set.workoutExercise
        set.markDeleted()
        guard let exercise else { return }
        for (index, survivor) in exercise.liveSets.enumerated() {
            guard survivor.order != index else { continue }
            survivor.order = index
            survivor.markEdited()
        }
        exercise.markEdited()
    }

    private func addSet() {
        let nextOrder = (workoutExercise.liveSets.map(\.order).max() ?? -1) + 1
        let newSet = WorkoutSet(order: nextOrder, restSeconds: defaultRestSeconds)
        newSet.workoutExercise = workoutExercise
        // context is shared via the environment; insert through the exercise's
        // context to keep this subview decoupled from @Environment.
        if let context = workoutExercise.modelContext {
            context.insert(newSet)
        }
    }
}

// MARK: - PreviousText formatter

/// Pure formatter for the "Previous" column. Split out so it can be reasoned
/// about and tested independently of SwiftUI. Shared by the workout screen and
/// the template editor via the `SetRow`'s `previousText` parameter.
enum PreviousText {

    /// The Previous column's string, rendered in `unit`.
    ///
    /// `prev.weight` is stored KILOGRAMS, like every weight in the app, so the
    /// unit is a required argument rather than a defaulted one. A default here
    /// would let a call site forget and get pounds-shaped numbers labelled
    /// correctly for somebody else — the exact silent failure canonical storage
    /// introduces, and the only one it introduces.
    static func format(_ prev: WorkoutHistory.PreviousSet?, in unit: WeightUnit) -> String {
        guard let prev else { return "—" }
        var parts: [String] = []
        if let w = prev.weight {
            parts.append(weightText(kilograms: w, in: unit))
        }
        if let r = prev.reps {
            parts.append("× \(r)")
        }
        // No load recorded — do not render a lone "(D)" / "(W)" / "(F)".
        // That would read as history when there is none.
        guard !parts.isEmpty else { return "—" }
        return parts.joined(separator: " ") + letterSuffix(for: prev.setType)
    }

    /// Suffixed only for lettered types. `.normal` is silent: most sets are
    /// normal, and the reference never tags them.
    private static func letterSuffix(for setType: SetType) -> String {
        switch setType {
        case .warmup:  return " (W)"
        case .dropSet: return " (D)"
        case .failure: return " (F)"
        case .normal:  return ""
        }
    }

    /// A stored weight rendered for a person: converted, formatted, and
    /// labelled — `135 lb`, `61.23 kg`.
    ///
    /// The one call every weight display should be making. Everything below it
    /// is a piece of this, exposed only because a couple of sites need a number
    /// without a label (an entry field) or a label without a number (a column
    /// header).
    static func weightText(kilograms: Double, in unit: WeightUnit) -> String {
        "\(formatWeight(displayValue(kilograms: kilograms, in: unit))) \(unit.abbreviation)"
    }

    /// Stored kilograms as the number to show in `unit`, rounded so a value the
    /// user typed survives the round trip.
    ///
    /// Named apart from `formatWeight` on purpose: this one CONVERTS and that
    /// one does not, and the two take the same type. Handing a kilogram value
    /// to `formatWeight` compiles cleanly and prints the wrong number.
    static func displayValue(kilograms: Double, in unit: WeightUnit) -> Double {
        WeightUnits.displayed(from: kilograms, in: unit)
    }

    /// Whole-number weights drop the trailing ".0"; otherwise show the value
    /// compactly (e.g. 85, 82.5, 61.23).
    ///
    /// **Takes a value ALREADY in the display unit.** It formats, it does not
    /// convert — see `displayValue(kilograms:in:)`.
    ///
    /// > **This used to be `String(value)` and that stopped being good enough
    /// > the moment storage became kilograms.** A pounds lifter's numbers are
    /// > whole and survived it; a KILOGRAM reader's do not. 135 lb stored is
    /// > 61.23496995 kg, and rounding that to `displayPrecision` lands on
    /// > 61.230000000000004 — because 0.01 has no exact binary form, so
    /// > `round(_:toNearest:)` multiplies the error back in on its way out.
    /// > `String` prints every digit of it. The screen read
    /// > `61.230000000000004 kg`.
    /// >
    /// > Counting in hundredths avoids the whole class: the rounding decides
    /// > how many decimals there are, and `String(format:)` decides how many
    /// > are printed, so no float ever reaches a string with its noise intact.
    /// > Two decimals is not a guess — it is `WeightUnits.displayPrecision`
    /// > spelled as digits, and the two have to stay in step.
    static func formatWeight(_ value: Double) -> String {
        let hundredths = (value * 100).rounded()
        if hundredths.truncatingRemainder(dividingBy: 100) == 0 {
            return String(Int(hundredths / 100))
        }
        if hundredths.truncatingRemainder(dividingBy: 10) == 0 {
            return String(format: "%.1f", hundredths / 100)
        }
        return String(format: "%.2f", hundredths / 100)
    }
}

// MARK: - Time formatting

/// m:ss for a duration in seconds. Used by the header timer and the rest
/// dividers.
private func formatTime(_ total: Int) -> String {
    let m = max(0, total) / 60
    let s = max(0, total) % 60
    return String(format: "%d:%02d", m, s)
}

// MARK: - RestProgressBar

/// Replaces a set's rest divider while that set's rest countdown is running:
/// a full-width accent bar that drains right-to-left as time runs out, with
/// the remaining time centred on it in `m:ss`. A thin light border outlines
/// it. Tapping the bar presents the timer controls.
private struct RestProgressBar: View {
    let timer: RestTimer
    let now: Date
    var onTap: () -> Void = {}

    private var remainingSeconds: Int {
        Int(timer.remaining(at: now).rounded())
    }

    var body: some View {
        GeometryReader { proxy in
            let progress = timer.progress(at: now)
            // `.leading` is load-bearing, not tidiness. A ZStack centers its
            // children by default, so shrinking the fill's width took the same
            // amount off BOTH edges and the bar closed toward the middle like
            // a pair of curtains instead of draining. Anchoring it left makes
            // the right edge the only one that moves, which is what a
            // depleting bar has to look like to be read as one.
            ZStack(alignment: .leading) {
                // Track
                Rectangle()
                    .fill(Theme.fieldFill)
                // Accent fill retreats right-to-left as time runs out.
                Rectangle()
                    .fill(Theme.accent)
                    .frame(width: proxy.size.width * progress)
                    .animation(.linear(duration: 1), value: progress)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .overlay {
                Text(formatTime(remainingSeconds))
                    .font(Typography.body.weight(.semibold))
                    .foregroundStyle(Theme.textPrimary)
                    .monospacedDigit()
            }
            .overlay(
                // Thin light border.
                Rectangle()
                    .stroke(Theme.textSecondary.opacity(0.4), lineWidth: 1)
            )
            .clipShape(.rect(cornerRadius: Radius.chip))
            .contentShape(Rectangle())
            .onTapGesture { onTap() }
        }
        .frame(height: 40)
        .padding(.vertical, Spacing.compact)
    }
}

// MARK: - RestControlsSheet

/// The timer control panel: a large Pause/Resume button, −15s / +15s, Reset,
/// and Skip. Presented from the top-bar timer button or by tapping a live
/// progress bar. Deliberately simple — a plain sheet, no alerts.
private struct RestControlsSheet: View {
    @Binding var restTimer: RestTimer
    let now: Date

    @Environment(\.dismiss) private var dismiss

    private var isPaused: Bool {
        restTimer.state == .paused
    }

    var body: some View {
        VStack(spacing: Spacing.spacious) {
            Text("Rest")
                .font(Typography.title)
                .foregroundStyle(Theme.textPrimary)

            Text(formatTime(Int(restTimer.remaining(at: now).rounded())))
                .font(Typography.title)
                .monospacedDigit()
                .foregroundStyle(Theme.accent)

            Button {
                if isPaused {
                    restTimer.resume(at: Date())
                } else {
                    restTimer.pause(at: Date())
                }
            } label: {
                Text(isPaused ? "Resume" : "Pause")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.primaryAction)
            .frame(maxWidth: .infinity)

            HStack(spacing: Spacing.comfortable) {
                Button {
                    restTimer.adjust(by: -15, at: Date())
                } label: {
                    Text("−15s")
                }
                .buttonStyle(.tintedAccent)

                Button {
                    restTimer.adjust(by: 15, at: Date())
                } label: {
                    Text("+15s")
                }
                .buttonStyle(.tintedAccent)
            }

            Button {
                restTimer.reset(at: Date())
            } label: {
                Text("Reset")
            }
            .buttonStyle(.tintedAccent)

            Button {
                restTimer.skip()
                dismiss()
            } label: {
                Text("Skip Rest")
            }
            .buttonStyle(.tintedDestructive)
        }
        .padding(.horizontal, Spacing.screenMargin)
        .padding(.vertical, Spacing.spacious)
        .frame(maxWidth: .infinity)
        .background(Theme.surface)
        .presentationDetents([.medium])
    }
}

// MARK: - Preview

#Preview {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(
        for: Exercise.self, Workout.self, WorkoutExercise.self, WorkoutSet.self,
        configurations: config
    )
    let context = container.mainContext

    let exercise = Exercise(
        name: "Back Squat",
        bodyPart: .legs,
        category: .barbell,
        focusMetric: .totalVolume
    )
    context.insert(exercise)

    let workout = Workout(name: "Afternoon Workout", startedAt: Date())
    context.insert(workout)

    let we = WorkoutExercise(order: 0, workout: workout, exercise: exercise)
    context.insert(we)
    context.insert(WorkoutSet(order: 0, weight: WeightUnits.kilograms(from: 135, in: .lbs), reps: 5, restSeconds: 90, workoutExercise: we))
    context.insert(WorkoutSet(order: 1, weight: WeightUnits.kilograms(from: 185, in: .lbs), reps: 5, restSeconds: 120, workoutExercise: we))
    context.insert(WorkoutSet(order: 2, setType: .warmup, restSeconds: 90, workoutExercise: we))

    // A preview must never schedule a real alert — see RestNotifications.
    return ActiveWorkoutScreen(restNotifications: NoRestNotifications(), workout: workout)
        .modelContainer(container)
}
